name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Start your Vite or React app as a service
      vite:
        image: node:alpine
        ports:
          - 5174:5174
        options: >-
          --workdir /app
          --entrypoint sh
          -c "npm install && npm run dev"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'  # Use your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Start the React app
        run: npm run dev &  # Start the React app in the background
      
      - name: Wait for the server to be ready
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:5174/; then  # Change to port 5174
              echo "Server is up!"
              break
            fi
            echo "Waiting for server to start..."
            sleep 5
          done

      - name: Run Cypress Tests
        run: npx cypress run --spec 'cypress/e2e/simple-test.cy.js'
