name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'  # Update to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npx cypress run --spec 'cypress/e2e/simple-test.cy.js'
